name = "SpatiallySymmetricTensors"
uuid = "267f34df-16a8-4a72-a26d-fb880b511394"
authors = ["Wei Tang <tangwei@smail.nju.edu.cn> and contributors"]
version = "0.1.4"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
KrylovKit = "0.9.2"
Revise = "3.7.3"
TensorKit = "0.14.3, 0.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
